import ExcelJS from 'exceljs'

// Generalized, professionally-formatted multi-sheet Excel export — same
// visual language (header block, table styling, totals row, negative-value
// conditional formatting) proven in exportStockStatementExcel.ts, but
// implemented independently so that file (and the Stock Statement report it
// serves) is never touched by other reports adopting this.

export type ProfessionalColumn = {
  header: string
  key: string
  width: number
  align: 'left' | 'center' | 'right'
  numFmt?: string
  isDate?: boolean
  negativeWarning?: boolean
  totalsFn?: 'sum'
  hidden?: boolean
}

export type ProfessionalSheetSpec = {
  sheetName: string
  title: string
  columns: ProfessionalColumn[]
  rows: Record<string, unknown>[]
  emptyMessage?: string
  /** Row indexes (0-based, matching `rows`) to render with the "opening balance" style. */
  highlightRowIndexes?: number[]
}

export type ProfessionalExportMeta = {
  companyName: string
  fromDate: string // YYYY-MM-DD, or '' if not date-scoped
  toDate: string // YYYY-MM-DD, or '' if not date-scoped
  filterLine: string
  generatedBy: string
}

function escapeText(value: string): string {
  return /^[=+\-@]/.test(value) ? `'${value}` : value
}

function sanitizeFilenamePart(s: string): string {
  return s.replace(/[\\/:*?"<>|]/g, '').trim().replace(/\s+/g, '_')
}

// ExcelJS serializes a Date cell from its raw getTime() (see
// dateToExcel in exceljs/lib/utils/utils.js) — timezone-agnostic, so a Date
// built from local midnight only round-trips correctly for browsers at
// UTC+0. For any timezone ahead of UTC (IST included), local midnight on the
// 24th is still the 23rd in absolute-time terms, so Excel shows the 23rd.
// Building from Date.UTC keeps the cell's absolute instant pinned to actual
// UTC midnight of the intended calendar date, independent of the browser's
// timezone.
function toDateOnly(iso: string): Date {
  const [y, m, d] = iso.split('-').map(Number)
  return new Date(Date.UTC(y, m - 1, d))
}

function formatDDMMMYYYY(iso: string): string {
  return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' })
    .format(toDateOnly(iso))
    .replace(/ /g, '-')
}

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } }
const HEADER_FONT: Partial<ExcelJS.Font> = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 }
const TITLE_FONT: Partial<ExcelJS.Font> = { bold: true, size: 16, color: { argb: 'FF1E3A5F' } }
const SUBTITLE_FONT: Partial<ExcelJS.Font> = { bold: false, size: 10, color: { argb: 'FF555555' } }
const THIN_BORDER: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: 'FFCCCCCC' } },
  left: { style: 'thin', color: { argb: 'FFCCCCCC' } },
  bottom: { style: 'thin', color: { argb: 'FFCCCCCC' } },
  right: { style: 'thin', color: { argb: 'FFCCCCCC' } },
}
const NEGATIVE_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFCE4E4' } }
const NEGATIVE_FONT: Partial<ExcelJS.Font> = { color: { argb: 'FF9B1C1C' }, bold: true }
const HIGHLIGHT_ROW_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF3F9' } }

export const QTY_FMT = '#,##0.000'
export const MONEY_FMT = '#,##0.00'

function applyReportHeader(
  sheet: ExcelJS.Worksheet,
  lastColLetter: string,
  title: string,
  meta: ProfessionalExportMeta
) {
  const mergeFullWidth = (row: number) => sheet.mergeCells(`A${row}:${lastColLetter}${row}`)
  const periodLabel = meta.fromDate && meta.toDate
    ? `Period: ${formatDDMMMYYYY(meta.fromDate)} to ${formatDDMMMYYYY(meta.toDate)}`
    : ''

  sheet.getCell('A1').value = meta.companyName
  sheet.getCell('A1').font = TITLE_FONT
  mergeFullWidth(1)

  sheet.getCell('A2').value = title
  sheet.getCell('A2').font = { bold: true, size: 13, color: { argb: 'FF333333' } }
  mergeFullWidth(2)

  sheet.getCell('A3').value = periodLabel
  sheet.getCell('A3').font = SUBTITLE_FONT
  mergeFullWidth(3)

  sheet.getCell('A4').value = meta.filterLine
  sheet.getCell('A4').font = SUBTITLE_FONT
  mergeFullWidth(4)

  sheet.getCell('A5').value = `Generated On: ${new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }).format(new Date())}   |   Generated By: ${escapeText(meta.generatedBy || '—')}`
  sheet.getCell('A5').font = SUBTITLE_FONT
  mergeFullWidth(5)

  for (let r = 1; r <= 5; r++) sheet.getRow(r).alignment = { vertical: 'middle' }
}

export function buildProfessionalSheet(workbook: ExcelJS.Workbook, meta: ProfessionalExportMeta, spec: ProfessionalSheetSpec) {
  const sheet = workbook.addWorksheet(spec.sheetName, {
    views: [{ state: 'frozen', xSplit: 0, ySplit: 7 }],
    pageSetup: {
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
      printTitlesRow: '1:7',
    },
  })

  const lastColLetter = sheet.getColumn(spec.columns.length).letter
  applyReportHeader(sheet, lastColLetter, spec.title, meta)

  const headerRowIdx = 7
  const headerRow = sheet.getRow(headerRowIdx)
  spec.columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1)
    cell.value = col.header
    cell.font = HEADER_FONT
    cell.fill = HEADER_FILL
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
    cell.border = THIN_BORDER
    const c = sheet.getColumn(i + 1)
    c.width = col.width
    if (col.hidden) c.hidden = true
  })
  headerRow.height = 32

  if (spec.rows.length === 0) {
    const msgRow = sheet.getRow(headerRowIdx + 1)
    msgRow.getCell(1).value = spec.emptyMessage || 'No records found for the selected filters.'
    sheet.mergeCells(`A${headerRowIdx + 1}:${lastColLetter}${headerRowIdx + 1}`)
    msgRow.getCell(1).font = { italic: true, color: { argb: 'FF888888' } }
    msgRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' }
    return
  }

  const dataRows = spec.rows.map((row) =>
    spec.columns.map((col) => {
      const v = row[col.key]
      if (v == null || v === '') return null
      if (col.isDate && typeof v === 'string') return toDateOnly(v)
      if (typeof v === 'string') return escapeText(v)
      return v as number
    })
  )

  const table = sheet.addTable({
    name: `${spec.sheetName.replace(/[^A-Za-z0-9]/g, '')}Table`,
    ref: `A${headerRowIdx}`,
    headerRow: true,
    totalsRow: true,
    style: { theme: 'TableStyleMedium2', showRowStripes: true },
    columns: spec.columns.map((col) => ({
      name: col.header,
      filterButton: true,
      totalsRowFunction: col.totalsFn,
      totalsRowLabel: col.key === spec.columns[0].key ? 'TOTAL' : undefined,
    })),
    rows: dataRows,
  })
  table.commit()

  // addTable overwrites header styling with its theme — reapply ours
  spec.columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1)
    cell.font = HEADER_FONT
    cell.fill = HEADER_FILL
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
    cell.border = THIN_BORDER
  })

  const firstDataRow = headerRowIdx + 1
  const lastDataRow = headerRowIdx + spec.rows.length
  const totalsRowIdx = lastDataRow + 1
  const highlightSet = new Set(spec.highlightRowIndexes ?? [])

  for (let r = firstDataRow; r <= lastDataRow; r++) {
    const row = sheet.getRow(r)
    const isHighlighted = highlightSet.has(r - firstDataRow)
    spec.columns.forEach((col, i) => {
      const cell = row.getCell(i + 1)
      cell.border = THIN_BORDER
      cell.alignment = { vertical: 'middle', horizontal: col.align, wrapText: false }
      if (col.isDate) cell.numFmt = 'dd-mmm-yyyy'
      else if (col.numFmt) cell.numFmt = col.numFmt
      if (isHighlighted) {
        cell.fill = HIGHLIGHT_ROW_FILL
        cell.font = { ...(cell.font ?? {}), italic: true }
      }
    })
  }

  const totalsRow = sheet.getRow(totalsRowIdx)
  totalsRow.eachCell((cell, colNumber) => {
    const col = spec.columns[colNumber - 1]
    cell.font = { bold: true }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8ECF3' } }
    cell.border = { ...THIN_BORDER, top: { style: 'medium', color: { argb: 'FF1E3A5F' } } }
    if (col?.numFmt) cell.numFmt = col.numFmt
    if (col) cell.alignment = { vertical: 'middle', horizontal: col.align }
  })

  const negWarningCols = spec.columns.map((c, i) => ({ c, i })).filter(({ c }) => c.negativeWarning)
  for (const { i } of negWarningCols) {
    const colLetter = sheet.getColumn(i + 1).letter
    sheet.addConditionalFormatting({
      ref: `${colLetter}${firstDataRow}:${colLetter}${lastDataRow}`,
      rules: [{ type: 'cellIs', operator: 'lessThan', formulae: ['0'], style: { fill: NEGATIVE_FILL, font: NEGATIVE_FONT }, priority: 1 }],
    })
  }

  sheet.headerFooter = {
    oddFooter: `&LGenerated: ${meta.toDate ? formatDDMMMYYYY(meta.toDate) : new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date())}&C&P of &N&R${meta.companyName}`,
  }
}

export async function exportProfessionalWorkbook(
  meta: ProfessionalExportMeta,
  sheets: ProfessionalSheetSpec[],
  filenameBase: string
): Promise<void> {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = meta.generatedBy || 'WareCore'
  workbook.created = new Date()

  for (const spec of sheets) {
    buildProfessionalSheet(workbook, meta, spec)
  }

  const buffer = await workbook.xlsx.writeBuffer()
  const parts = [sanitizeFilenamePart(filenameBase)]
  if (meta.fromDate && meta.toDate) {
    parts.push(formatDDMMMYYYY(meta.fromDate), 'to', formatDDMMMYYYY(meta.toDate))
  }
  downloadBuffer(buffer, `${parts.join('_')}.xlsx`)
}

function downloadBuffer(buffer: ExcelJS.Buffer, filename: string) {
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
