// Purchase (Bill) ID generation — shared by the manual entry form
// (src/app/(app)/bills/new/page.tsx) and the bulk Excel import
// (src/lib/purchaseImport/) so both paths compute IDs identically and can
// never silently drift apart, which would risk colliding bill_number /
// purchase_line_id values between manual and imported bills.
//
// Neither purchase_bills.bill_number nor purchase_bill_items.purchase_line_id
// is generated by a DB trigger or sequence — both are plain, deterministic
// functions of "what IDs already exist", computed here and passed in on
// INSERT. See docs/data-integrity/CURRENT_STATE_AUDIT.md for the wider
// ledger-posting context this feeds into.

// PurchaseID/SaleID format: MMYY-NNNN (see ID Format Rules).
export function getMMYY(date: Date = new Date()): string {
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const yy = String(date.getFullYear()).slice(-2)
  return `${mm}${yy}`
}

export function computeNextSeq(ids: string[], pattern: RegExp): number {
  return ids.reduce((max, id) => {
    if (!id) return max
    const m = id.match(pattern)
    return m ? Math.max(max, parseInt(m[1], 10)) : max
  }, 0)
}

export function generatePurchaseId(existingBillNumbers: string[], dateStr?: string): string {
  const seq = computeNextSeq(existingBillNumbers, /^\d{4}-(\d+)$/)
  const date = dateStr ? new Date(dateStr + 'T00:00:00') : new Date()
  return `${getMMYY(date)}-${String(seq + 1).padStart(4, '0')}`
}

// Line ID format: {GroupCode2}{MMYY}-NNNN, where GroupCode2 is the first two
// letters of the material type's code, uppercased.
export function generatePurchaseLineId(groupCode: string, mmyy: string, allLineIds: string[]): string {
  const prefix = `${groupCode.slice(0, 2).toUpperCase()}${mmyy}-`
  const count = allLineIds.filter((id) => id && id.startsWith(prefix)).length
  return `${prefix}${String(count + 1).padStart(4, '0')}`
}
